version: "2"

services:
    ngrok:
        image: wernight/ngrok
        volumes:
          - .:/var/www
        networks:
            - adsdaq_proxy-tier
        expose:
            - '4040'
        depends_on:
            - nginx

        environment:
            VIRTUAL_HOST: ngrok.dev

        command: ngrok start --config /var/www/ngrok.yml --all

    application:
        image: debian:jessie
        volumes:
            - .:/var/www/confluence-client

    nginx:
        image: he8us/nginx
        expose:
            - "80"
        environment:
            VIRTUAL_HOST: confluence-client.dev
            DOCUMENT_ROOT: /var/www/confluence-client
            LOG_FILE: confluence-client
        volumes_from:
            - application
        depends_on:
            - php
        networks:
            - adsdaq_proxy-tier



    php:
        image: he8us/php-fpm-dev:7.0
        expose:
            - "9000"
        environment:
            APPLICATION_ENV: dev
            TIMEZONE: "Europe/Brussels"
        volumes_from:
            - application
        networks:
            - adsdaq_proxy-tier


networks:
    adsdaq_proxy-tier:
      external: true
